### PR TITLE
chore(docs): refresh compatibility matrix

### LINKED ISSUE #1069: The compatibility-matrix needs to up to 1.28 in readme.md
The compatibility-matrix needs to up to 1.28 in readme.md.

Should it update to v1.23.x ？

(https://github.com/kubernetes/client-go#compatibility-matrix)

### PR DESCRIPTION
**Pull request by dnwe**
Bring the compatibility matrix up-to-date with more recent versions of Kubernetes

Fixes #1069

### CODE REVIEW

**Comment by dnwe** [comment]
@yliaog seems like 'pull-client-go-build' is using a go version older than 1.16 and hence can't find the io/fs pkg (that was new in 1.16). I guess this build infra hasn't been updated in a while as changes don't usually come direct to this repo

**Comment by dnwe** [comment]
@yliaog can we revisit this?

**Comment by yliaog** [comment]
could you rebase the PR?

**Comment by dnwe** [comment]
As previously mentioned, the pull-client-go-build is broken because it's still using Go 1.16 and the master branch of client-go needs at least 1.21 now due to a dependency on the builtin `cmp` package

I raised https://github.com/kubernetes/test-infra/pull/31713 to bump it

**Comment by cblecker** [comment]
@yliaog looks like this one is ready for review again

/triage accepted

**Comment by yliaog** [comment]
1.29 has been released, and should be added, but that can be done later.

**Pull request merged**
