### PR TITLE
Example Added to create update and delete service

### PR DESCRIPTION
**Pull request by shantanubansal**
Added an example for creating, updating, list and deleting a service.

README:

# Create, Update & Delete Service

This example program demonstrates the fundamental operations for managing on
[Service][1] resources, such as `Create`, `List`, `Update` and `Delete`.

You can adopt the source code from this example to write programs that manage
other types of resources through the Kubernetes API.

## Running this example

Make sure you have a Kubernetes cluster and `kubectl` is configured:

    kubectl get nodes

Compile this example on your workstation:

```
cd create-update-delete-service
go build -o ./app
```

Now, run this application on your workstation with your local kubeconfig file:

```
./app
# or specify a kubeconfig file with flag
./app -kubeconfig=$HOME/.kube/config
```

Running this command will execute the following operations on your cluster:

1. **Create service:** This will create a  Service. Verify with
   `kubectl get services`.
2. **Update Service:** This will update the Service resource created in
   previous step by changing the type of servicr
   `kubectl describe service demo`.
3. **List Services:** This will retrieve Services in the `default`
   namespace and print their names and type.
4. **Delete Service:** This will delete the Service object. Verify with `kubectl get services`.

Each step is separated by an interactive prompt. You must hit the
<kbd>Return</kbd> key to proceed to the next step. You can use these prompts as
a break to take time to run `kubectl` and inspect the result of the operations
executed.

You should see an output like the following:

```
Creating Service...
Created service "demo-service".
-> Press Return key to continue.

Updating Service...
Updated service...
-> Press Return key to continue.

Listing services in namespace "default":
 * demo-services (NodePort)
-> Press Return key to continue.

Deleting service...
Deleted service.
```

## Cleanup

Successfully running this program will clean the created artifacts. If you
terminate the program without completing, you can clean up the created
service with:

    kubectl delete service demo-service

## Troubleshooting

If you are getting the following error, make sure Kubernetes version of your
cluster is v1.6 or above in `kubectl version`:

    panic: the server could not find the requested resource

[1]: https://kubernetes.io/docs/user-guide/service/

### CODE REVIEW

**Comment by shantanubansal** [comment]
/cla/linuxfoundation

**Comment by shantanubansal** [comment]
@dims what steps I have to take next to get his reviewed and merged?

**Comment by dims** [comment]
@shantanubansal talk to the assignees in apimachinery slack channel / show up in their weekly meeting if you don't hear from anyone in a few days.

**Comment by knight42** [comment]
/hold

This repo is a read-only mirror.

**Comment by shantanubansal** [comment]
Yep closing it and creating it in the staging area

**Comment by caesarxuchao** [comment]
Yep, please open a PR against the staging directory in k/k.

Also what additional information does this example add, compared to the existing [create-update-delete-deployment](https://github.com/kubernetes/client-go/tree/master/examples/create-update-delete-deployment) example?

**Comment by shantanubansal** [comment]
I am closing the PR. will create at the appropriate repo

**Comment by james-elastic** [comment]
Thanks @shantanubansal your create-update-delete-service example helped me today!

**Comment by shantanubansal** [comment]
> Thanks @shantanubansal your create-update-delete-service example helped me today!

@james-elastic Adding PR to staging area. If it was useful to you maybe will be helpful to many others.
Thanks :)

**Comment by shantanubansal** [comment]
Created PR for k/k
https://github.com/kubernetes/kubernetes/pull/102961

**Pull request closed without merging**
