### PR TITLE
Update example README.md

### PR DESCRIPTION
**Pull request by Asuforce**
When using minikube, you need to specify the tag.

### CODE REVIEW

**Comment by Asuforce** [comment]
@yliaog Would you please merge this pr ?

**Comment by nikhita** [comment]
@Asuforce Thanks for the PR! This repo is a copy of https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go. Please submit PRs to the kubernetes/kubernetes repo directly, in particular to the file [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/examples/in-cluster-client-configuration/README.md).

**Comment by Asuforce** [comment]
@nikhita ok ! I'll do it !

**Pull request closed without merging**
