### PR TITLE
Sync with k8s.io/kubernetes/staging

### PR DESCRIPTION
**Pull request by caesarxuchao**
Sync with k8s.io/kubernetest at 17375fc59fff39135af63bd1750bb07c36ef873b, and k8s.io/apimachinery at d90aa2c8531f13b0ca734845934c10dcb6a56ca7

Updated the CHANGELOG accordingly. Please let me know if I missed any important changes.

Fix https://github.com/kubernetes/client-go/issues/123.

@deads2k @DirectXMan12 @sttts @lavalamp

### CODE REVIEW

**Comment by deads2k** [comment]
Thanks

**Comment by deads2k** [comment]
file list looks right.

**Comment by caesarxuchao** [comment]
@lavalamp our most of INSTALL.md instructs people using v2.0.0, so this pull doesn't affect INSTALL.md

I manually verified `go get` still works (though still has the known issues). I also manually verified if I pin to the latest commit of client-go in glide.yaml, `glide up -v` still works.

**Comment by lavalamp** [comment]
thank you!

**Pull request merged**
