### PR TITLE
remove 1.5 folder from 1.4 branch

### PR DESCRIPTION
**Pull request by caesarxuchao**
@lavalmap @timoreimann I made the 1.4 branch, and remove the 1.5 folder from it. I want to keep the 1.4 folder instead of moving things out, because this way users don't need to change their import lines.

I want to make a 1.5 branch as well, because 1.5 fixed some issues in 1.4 (like the auth plugin), I think 1.5 has some users.

### CODE REVIEW

**Comment by timoreimann** [comment]
@caesarxuchao do we plan to remove the top level 1.x branch in some release? My understanding is that we need to do this in order to enable import path rewrite-free upgrades.

**Comment by caesarxuchao** [comment]
I see. I want to keep the top level folder for 1.4 and 1.5 only, so people who are already using them do not need to rewrite import path.
Next release will be v2, and we won't keep the top level folder anymore. Does this work?

**Comment by timoreimann** [comment]
Sounds reasonable to me.

Another question: Are we not going to continue matching the client version with the Kubernetes version it was carved out of? When we do v2.0, how will users know what features they can expect to be included in the client?

I realize it's actually very common to not tie the client semver version to the server version and communicate new features via documentation and such. I'm just wondering if we have an opportunity for a more strict matching since the client is basically a copy of some files from the main kubernetes repo. (But maybe we're not going to do that in the future anymore?)

I suppose I'm just missing a key point here. Feel also free to point me at another discussion forum if your PR is not the most suitable place to ask such generic questions.

**Comment by caesarxuchao** [comment]
> Are we not going to continue matching the client version with the Kubernetes version it was carved out of? 

No. I think the client will evolve faster than the kuberentes main repository

> When we do v2.0, how will users know what features they can expect to be included in the client?

I think you are asking how users know what versions of kubernetes cluster a version of client-go is compatible with? I think we need a compatibility matrix (like in https://github.com/kubernetes/client-go/pull/7#discussion_r81039643).

A version of clinet-go will be compatible with many versions of kubernetes cluster, backward and forward. But to use all features provided by a kubernetes release, users will need to use the client-go released later or at the same time of the kubernetes release. We will document this information as well.

**Comment by mbohlool** [comment]
LGTM

**Comment by caesarxuchao** [comment]
The PR is created against `master`. Will close and create another one again 1.4 branch.

**Comment by timoreimann** [comment]
@caesarxuchao FYI, Github introduced rebasing for PRs a while ago so you don't need to close and recreate anymore when you picked the wrong base.

**Comment by caesarxuchao** [comment]
That's a nice feature. Thanks for letting me know :)

**Pull request closed without merging**
