### PR TITLE
Update example README.md (fix typo)

### PR DESCRIPTION
**Pull request by imazik**
add missing `"` in import path

### CODE REVIEW

**Comment by imazik** [comment]
I have signed the CLA.

**Comment by imazik** [comment]
I signed it

**Comment by imazik** [comment]
I signed it

**Comment by imazik** [comment]
I signed it

**Comment by imazik** [comment]
I signed it

**Comment by nikhita** [comment]
Oops I thought this was the main README. The right way to update this is https://github.com/kubernetes/kubernetes/pull/77659

**Pull request closed without merging**
