### PR TITLE
Fix links to examples in README.md

### PR DESCRIPTION
**Pull request by tomdee**

### CODE REVIEW

**Comment by tomdee** [comment]
hi @k8s-ci-robot can you recheck this PR?

**Comment by johnharris85** [comment]
LGTM

**Comment by jarthorn** [comment]
Was about to submit the same patch then I noticed this PR. cc @ahmetb the links were broken by https://github.com/kubernetes/kubernetes/pull/46883

**Comment by ahmetb** [comment]
Sorry I must have missed this README. /lgtm

**Comment by sebgoa** [comment]
this should be merge, was submitting the same PR.

**Comment by caesarxuchao** [comment]
Thanks. I merged https://github.com/kubernetes/client-go/pull/261.

**Pull request closed without merging**
