### PR TITLE
Add GoReportCard badge

### PR DESCRIPTION
**Pull request by asifdxtreme**

### CODE REVIEW

**Comment by asifdxtreme** [comment]
@lavalamp can you please help me to merge this PR

**Comment by asifdxtreme** [comment]
@caesarxuchao @deads2k @krousey @lavalamp @smarterclayton @sttts  can you please help me to merge this PR

**Comment by sttts** [comment]
lgtm

**Comment by sttts** [comment]
@caesarxuchao can you merge?

**Comment by caesarxuchao** [comment]
Thanks @asifdxtreme. Could you squash?

**Comment by sttts** [comment]
@asifdxtreme ping

**Comment by asifdxtreme** [comment]
@sttts sorry for late reply....I have squashed my current commit.....Thanks

**Pull request merged**
