### PR TITLE
Fix broken link to api-conventions doc.

### PR DESCRIPTION
**Pull request by Hyzhou**
Signed-off-by: misakazhou <misakazhou@tencent.com>

The broken link make a little trouble. What about to fix it?
PS: I already checked other link from https://git.k8s.io/community/ :)

### CODE REVIEW

**Comment by Hyzhou** [comment]
I signed it

**Comment by Hyzhou** [comment]
I signed it

**Comment by Hyzhou** [comment]
I signed it

**Comment by sttts** [comment]
PR looks good. Though, please open it against github.com/kubernetes/kubernetes staging/src/k8s.io/client-go. This copy here is just published, it's not authorative.

**Comment by Hyzhou** [comment]
Thanks, I get it.

**Pull request closed without merging**
