### PR TITLE
Generated by robot

### PR DESCRIPTION
**Pull request by caesarxuchao**
First two commits are manually written to sync client-go up to a state that could be further updated by the publish script.

@sttts Original Kubernetes-commit are included in the commit messages ^^

All 5 PRs generated in the same run of the robot:
https://github.com/kubernetes/client-go/pull/140
https://github.com/kubernetes/apimachinery/pull/10
https://github.com/kubernetes/apiserver/pull/4
https://github.com/kubernetes/kube-aggregator/pull/4
https://github.com/kubernetes/sample-apiserver/pull/2

### CODE REVIEW

**Comment by caesarxuchao** [comment]
I don't think we need to fix travis. It's use `go get`, which should be fixed by this series of PRs. Travis should pass after https://github.com/kubernetes/apimachinery/pull/9 gets merged.

**Comment by mbohlool** [comment]
All of the code in this PR is code reviewed before and looks good. After travis-ci reports green, it should be good to merge.

**Comment by pmorie** [comment]
Travis build errored:

```
pkg/api/helpers.go:247: undefined: v1.FinalizerOrphanDependents
```

This is because the apimachinery repo is out of sync with the core -- I believe we need to update the `apimachinery` repo before this will work.

**Comment by caesarxuchao** [comment]
@pmorie yes, that's what kubernetes/apimachinery#9 does.

**Comment by caesarxuchao** [comment]
Trigger travis, it should be green now.

**Comment by caesarxuchao** [comment]
Now fails with:
```
github.com/emicklei/go-restful (download)
package github.com/emicklei/go-restful/swagger: cannot find package "github.com/emicklei/go-restful/swagger" in any of:
	/home/travis/.gimme/versions/go1.7.4.linux.amd64/src/github.com/emicklei/go-restful/swagger (from $GOROOT)
	/home/travis/gopath/src/github.com/emicklei/go-restful/swagger (from $GOPATH)
github.com/golang/glog (download)
```

**Comment by caesarxuchao** [comment]
Eh, the vendor/ folder is missing.. this break `go get` users of client-go.

I'll merge it as is, since other repos are referencing the commit in this PR.

I'll send another bunch of PRs to add the vendor/ back to client-go.

**Comment by brancz** [comment]
Can we expect to see a release with the 1.6 compatible changes some time soon? Or is it safe to vendor current master and not having to fix lots of changes once there is a release including these changes?

**Pull request merged**
