### PR TITLE
Cherry-pick fixes to release 2.0

### PR DESCRIPTION
**Pull request by caesarxuchao**
CHANGELOG:
clientset supports multiple versions per group
apps & policy group graduate to v1beta1

I'll make v2.0.0 after this PR gets merged.  

After this PR gets merged, the release-2.0 branch is roughly tracking the kubernetes/release-1.5 branch. I'll manually cherry-pick bug fixes to the release-2.0 branch, and create v2.x.0 tags. (It seems we should name the branch release-2 instead of release-2.0)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@mbohlool could you make a sanity check? Thanks.

**Comment by mbohlool** [comment]
It is too huge to review. Look like everything is reviewed in the main repo. I would say just go ahead and merge it (one of the original contributors need to sign the CLA I guess)

**Comment by caesarxuchao** [comment]
@foxish do you know how can see which author doesn't sign the CLA? Currently it just says `dtan4 authorized, but 1 other problem`. Or is it because I cherry-picked the commits?

**Comment by foxish** [comment]
@caesarxuchao Looks like the publisher bot is the one that has not signed the CLA. Hovering over the status next to each commit tells us that it is missing email on its commits as well.

**Pull request merged**
