### PR TITLE
Rewording for clarity

### LINKED ISSUE #419: Interesting Readme language
Please read the first part of the README.md file carefully...

capture

### PR DESCRIPTION
**Pull request by mistyhacks**
Signed-off-by: Misty Stanley-Jones <mistyhacks@google.com>

Fixes #419 

Yes I read the notice below, but the `README.md` is not in `kubernetes/kubernetes` (or I certainly can't find it), so I think this is the only way to fix this.

```
Sorry, we do not accept changes directly against this repository. Please see 
CONTRIBUTING.md for information on where and how to contribute instead.
```

### CODE REVIEW

**Comment by cblecker** [comment]
/assign @sttts 
Looks like the README file is missing from the staging dir in k/k. How should we handle this?

**Comment by nikhita** [comment]
Fwiw I have been creating PRs to change the README every release (this is after publishing bot came into existence) and they get manually merged: https://github.com/kubernetes/client-go/pull/391, https://github.com/kubernetes/client-go/pull/389, https://github.com/kubernetes/client-go/pull/341

> Looks like the README file is missing from the staging dir in k/k.

But we should still fix this. client-go is the only outlier in staging dirs which doesn't have all files in staging. I'll comment on https://github.com/kubernetes/kubernetes/issues/54398.

**Comment by sttts** [comment]
@caesarxuchao we still have the README in the client-go repo. The reasons for that are still valid: we have to change it post-release, and independently from point releases of kube.

**Pull request merged**
