### PR TITLE
Round2: Generated by scripts

### PR DESCRIPTION
**Pull request by caesarxuchao**
Last round of PRs failed to update vendor/. This one fixed it.

In last round, a manual commit removed the vendor/, due to the bug, the robot didn't add back the vendor/. This PR added it back.

@deads2k @sttts cc @mbohlool 

PRs to other repos:
https://github.com/kubernetes/apiserver/pull/5
https://github.com/kubernetes/kube-aggregator/pull/5
https://github.com/kubernetes/sample-apiserver/pull/3
https://github.com/kubernetes/client-go/pull/154
https://github.com/kubernetes/apimachinery/pull/11

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm.  let me know about merge.

**Comment by caesarxuchao** [comment]
Verified client-go can compile when only client-go, apimachinery, and glog are in the GOPATH.

**Comment by caesarxuchao** [comment]
Travis passed, indicating `go get k8s.io/client-go` in a clean GOPATH will result in code that compiles.

**Comment by caesarxuchao** [comment]
I also verified the robot will continue to work after these changes are merged.

One annoying thing is that the robot will push a pair of `sync: reset Godeps.json` and `sync: resync vendor folder` commits even if there is no new changes. cc @deads2k

**Comment by caesarxuchao** [comment]
We can `git diff HEAD~~ HEAD` to dedup.

**Comment by deads2k** [comment]
> We can git diff HEAD~~ HEAD to dedup.

That sounds like a good idea.

**Comment by deads2k** [comment]
merging for script

**Pull request merged**
